disabled_rules:
    - opening_brace
    - function_body_length
opt_in_rules:
    - anyobject_protocol
    - convenience_type
identifier_name:
    min_length: 2
    excluded: # excluded via string array
        - id
        - URL
        - x
        - y
custom_rules:
    empty_line_after_guard: # from https://github.com/brandenr/swiftlintconfig
        name: 'Empty Line After Guard'
        regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}\n *(?!(?:return|guard))\S+)'
        message: 'There should be an empty line after a guard'
        severity: warning
